services:
  hub:
    container_name: "LGSM-SLMS"
    build: .
    ports:
      - "49950:49950"
    volumes:
      - ./data:/app/data
      - ../spoke:/app/static/spoke
    environment:
      - SECRET_KEY=lgsm-secure-key-123
      - DB_PATH=/app/data/hub.db
    restart: always
